stages:
  - build
  - deploy

variables:
  NODE_VERSION: "20.x"
  SERVER_IP: "coonh.de"
  FRONTEND_PATH: "/var/www/html/hunt"
  BACKEND_PATH: "/var/www/assassin-party"

build_frontend:
  stage: build
  image: node:$NODE_VERSION
  script:
    - cd frontend
    - npm install
    - npm run build -- --base-href /hunt/
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour
  only:
    - main

deploy_job:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y sshpass openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # Deploy Frontend
    - rsync -atv --delete frontend/dist/frontend/browser/ $SERVER_USER@$SERVER_IP:$FRONTEND_PATH
    
    # Deploy Backend
    - rsync -atv --delete --exclude 'node_modules' backend/ $SERVER_USER@$SERVER_IP:$BACKEND_PATH
    
    # Restart Backend with PM2
    - ssh $SERVER_USER@$SERVER_IP "cd $BACKEND_PATH && npm install --production && pm2 restart server || pm2 start server.js --name server"
  only:
    - main
